//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Mach4.rc
//
#pragma warning(disable:4005)


#define IDS_MACH1OCX                    1
#define IDD_ABOUTBOX_MACH1OCX           2
#define IDB_MACH1OCX                    3
#define IDS_MACH1OCX_PPG                4
#define IDCONFIG                        5
#define IDS_MYSCRIPT                    6
#define IDM_ABOUTBOX                    16
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             101
#define IDS_ABOUTBOX                    102
#define IDD_MACH1CONTROL_DIALOG         103
#define IDP_SOCKETS_INIT_FAILED         104
#define IDD_PROPPORTSETUP               105
#define IDR_HTML_MACRORUN               106
#define EXTERNAL_COMMAND                107
#define IDB_ONOFF                       111
#define IDB_BACKGROUND                  112
#define IDD_DIAGNOSTIC                  113
#define IDR_DIAGMENU                    114
#define IDD_UNITS                       116
#define IDB_BALL                        118
#define IDD_HOTKEY                      120
#define IDS_MACH1OCX_PPG_CAPTION        125
#define IDD_PROPPAGE_MACH1OCX           126
#define ID_VIEW_ARRANGE                 127
#define IDR_MAINFRAME                   128
 
#define IDR_GCodeTYPE                   130
#define IDC_ENC2                        131
#define IDC_INCREMENTAL                 132
#define IDC_ENC3                        133
#define IDC_IJMODE1                     134
#define IDD_SCRIPTCONTROL               135
#define IDC_QUEUEDEPTH                  136
#define IDR_DISPOPUP                    137
#define IDD_CALMPG                      138
#define IDC_DONE                        139
#define IDR_MDILIST                     140
#define IDC_PAUSED                      141
#define IDD_G200X                       142
#define IDD_HOTKEYS                     143
#define IDC_TERM                        144
#define IDD_SETIP                       145
#define IDB_PLAY                        146
#define IDD_MACRODUMMY                  147
#define IDC_SPEED                       148
#define IDD_HOMANN                      149
#define IDC_ADDLINE                     150
#define IDC_LINEVAL1                    151
#define IDD_BUGREPORT                   152
#define IDC_LINEVAL2                    153
#define IDD_GECKOAXIS                   154
#define IDC_LINEVAL3                    155
#define IDC_LINEVAL4                    156
#define IDC_LINEVAL5                    157
#define IDC_LINEVAL6                    158
#define IDR_VBBAR                       159
#define IDB_INCHES                      160
#define IDC_ADDCIRCLE                   161
#define IDC_CENTERX                     162
#define IDD_TORCH                       163
#define IDC_CENTERY                     164
#define IDD_MODBUS2                     165
#define IDC_CENTERZ                     166
#define IDD_VIDEO                       167
#define IDC_HOLD                        168
#define IDB_GREENBUTTON                 169
#define IDD_SERIALRING                  170
#define IDC_PAUSE                       171
#define IDC_RESUME                      172
#define IDD_TEXTQUESTION                173
#define IDC_ZERO                        174
#define IDD_FONTS                       175
#define IDD_RESETWARN                   176
#define IDC_FEEDRATE                    177
#define IDD_MODSETDIALOG                178
#define IDD_PLUGINS                     179
#define IDC_GOTOZEROS                   180
#define IDD_PORTS                       181
#define IDD_BACKLASH                    182
#define IDD_TOOLTABLE                   183
#define IDD_TAKEOVERMOTION              184
#define IDC_RUN                         185
#define IDC_3                           186
#define IDD_PULLEYS                     187
#define IDC_IJMODE                      188
#define IDC_REFERENCE                   189
#define IDD_SAFEZ                       190
#define IDC_4                           191
#define IDD_NORMALS                     192
#define IDC_PLANE                       193
#define IDC_5                           194
#define IDC_TOOLRADIUS                  195
#define IDC_OVERRIDE                    196
#define IDD_DROCALC                     197
#define IDC_TOOLLENGTH                  198
#define IDC_POINT001                    199
#define IDR_MENU2                       200
#define IDC_PLAY                        201
#define IDC_POINT002                    202
#define IDC_STOP                        203
#define IDC_POINT003                    204
#define IDC_DEFAULTS                    205
#define IDI_TURN2                       206
#define IDC_REWIND                      207
#define IDD_RESTORESETTINGS             208
#define IDC_POINT004                    209
#define IDD_DISCLAIMER                  210
#define IDC_POINT005                    211
#define IDR_WAVE1                       212
#define IDC_GCODEDISPLAY                213
#define IDC_SINGLE                      214
#define IDD_SETUPINPUT                  215
#define IDC_FILENAME                    216
#define IDD_LIC1                        217
#define IDC_FILESLIDE                   218
#define IDD_SERVOTUNE                   219
#define IDC_CURRENTLINE                 220
#define IDC_CURRENTEXEC                 221
#define IDD_TCPMODBUS                   222
#define IDC_DISPEXEC                    223
#define IDC_STATUS                      224
#define IDD_BRAINS                      225
#define IDC_GC                          226
#define IDR_BRAINMENU                   227
#define IDC_XLIMP                       228
#define IDR_BRAINBAR                    229
#define IDC_RADIO16                     230
#define IDC_ZLIMP                       231
#define IDC_MIST                        232
#define IDC_RADIO22                     233
#define IDC_RADIO23                     234
#define IDC_ZLIMM                       235
#define IDC_ESTIMATED                   236
#define IDC_MINY                        237
#define IDC_MAXY                        238
#define IDC_LIST1                       239
#define IDC_SETFIXTURE                  240
#define IDC_USEOFFSETOFF                241
#define IDC_ACTIVATE                    242
#define IDC_HOTOFF                      243
#define IDC_HOTON                       244
#define IDC_SINGLED                     245
#define IDC_RESUMED                     246
#define IDC_ZEROXD                      247
#define IDC_ZEROYD                      248
#define IDC_ZEROZD                      249
#define IDC_ZEROAD                      250
#define IDC_ZEROBD                      251
#define IDC_ISO2                        252
#define IDC_ISO3                        253
#define IDC_SIMULATE                    254
#define IDC_MACRONAME                   255
#define IDD_ANCILLARY                   256
#define IDR_HTML_GECK2002DLG            257
#define IDR_HTML_HELPMENU               258
#define IDR_HTML_MODBUSSTATUS           259
#define IDC_INCREMENT                   260
#define IDC_INCFEED                     261
#define IDC_SLIDER1                     262
#define IDC_ACCELSLIDE                  263
#define IDC_MOVEMENT                    264
#define IDC_XPLUS                       265
#define IDD_FIXTURES                    266
#define IDD_SAFEMOVE                    267
#define IDD_QUESTION                    268
#define IDC_XMINUS                      269
#define IDC_YMINUS                      270
#define IDC_ZMINUS                      271
#define IDB_NONE                        272
#define IDC_AMINUS                      273
#define IDB_ORIGIN1                     274
#define IDC_BMINUS                      275
#define IDB_ORIGIN2                     276
#define IDC_CMINUS                      277
#define IDD_DIGITIZE                    278
#define IDD_ADDONS                      279
#define IDC_YPLUS                       280
#define IDC_ZPLUS                       281
#define IDC_APLUS                       282
#define IDD_PASSWORD                    283
#define IDC_BPLUS                       284
#define IDD_SLAVE                       285
#define IDC_CPLUS                       286
#define IDC_PERCENT                     287
#define IDC_ZEROX                       288
#define IDC_ZEROY                       289
#define IDC_POINT01                     290
#define IDC_ZEROZ                       291
#define IDC_POINT02                     292
#define IDC_ZEROA                       293
#define IDC_POINT03                     294
#define IDC_ZEROB                       295
#define IDC_POINT04                     296
#define IDC_ZEROC                       297
#define IDC_POINT05                     298
#define IDC_SPINDLECW                   299
#define IDB_LEDGREEN                    300
#define IDC_POINT1                      301
#define IDB_LEDRED                      302
#define IDC_CHARGE                      303
#define IDB_LEDYELLOW                   304
#define IDC_SPINDLECCW                  305
#define IDC_POINT2                      306
#define IDC_SPINDLEOFF                  307
#define IDC_POINT3                      308
#define IDC_CONSTANT                    309
#define IDD_RUNFROM                     310
#define IDC_ZEROALL                     311
#define IDC_POINT4                      312
#define IDD_PATHPROGRESS                313
#define IDC_EXACTSTOP                   314
#define IDC_POINT5                      315
#define IDC_COMPENSATE                  316
#define IDC_INCRTOGGLE                  317
#define IDC_1                           318
#define IDD_DXF_DIALOG                  319
#define IDC_LEFT                        320
#define IDC_RESET                       321
#define IDD_LAYERDIALOG                 322
#define IDC_2                           323
#define IDC_DISTANCEMODE                324
#define IDB_IMAGES                      325
#define IDC_OVERPERCENT                 326
#define IDC_SETEXEC                     327
#define IDD_RUTEX                       328
#define IDC_OVERRESET                   329
#define IDC_GA                          330
#define IDC_ERROR                       331
#define IDD_GETCOORDs                   332
#define IDC_GB                          333
#define IDC_CHANGE                      334
#define IDD_MRULIST                     335
#define IDC_SYNC                        336
#define IDC_GX                          337
#define IDC_GY                          338
#define IDC_GZ                          339
#define IDC_ZREV                        340
#define IDC_CREV                        341
#define IDC_XREV                        342
#define IDD_TOOLCONFIG                  343
#define IDC_YREV                        344
#define IDD_HELPER                      345
#define IDC_DIGTRIG                     346
#define IDD_DIALOG1                     347
#define IDD_MOTORCONFIG                 348
#define IDC_DWELL                       349
#define IDC_XZ                          350
#define IDC_YZ                          351
#define IDD_INPUTSIGS                   352
#define IDC_RIGHT                       353
#define IDD_OUTPUTSIGS                  354
#define IDC_SPINCCW                     355
#define IDD_ENCODERS                    356
#define IDC_SPINCW                      357
#define IDD_MOTOROUTS                   358
#define IDC_RADIO3                      359
#define IDD_SPINDLE                     360
#define IDC_RADIO5                      361
#define IDD_MILLOPTIONS                 362
#define IDC_BLIMP                       363
#define IDD_INPUTSIGS2                  364
#define IDD_TURNOPTIONS                 365
#define IDC_RADIO19                     366
#define IDD_SETTINGS_DLG                367
#define IDC_RADIO20                     368
#define IDD_DOHELP                      369
#define IDC_SPINSECONDS                 370
#define IDB_TOOLS                       371
#define IDC_NOSPINDLE                   372
#define IDC_FLOOD                       373
#define IDC_YLIMP                       374
#define IDC_RADIO21                     375
#define IDC_ALIMP                       376
#define IDC_CLIMP                       377
#define IDC_XLIMM                       378
#define IDC_YLIMM                       379
#define IDC_NOFLOODMIST                 380
#define IDD_MODBUS                      381
#define IDC_ALIMM                       382
#define IDC_CLIMM                       383
#define IDC_ZHOME                       384
#define IDC_AHOME                       385
#define IDC_CHOME                       386
#define IDC_BOUNDRIES                   387
#define IDD_DIALOG2                     388
#define IDC_LICENSE                     389
#define IDD_MODBUSSTATUS                390
#define IDC_REFX                        391
#define IDD_SPINCAL                     392
#define IDC_REFY                        393
#define IDC_REFZ                        394
#define IDD_MAINTENANCE                 395
#define IDC_REFA                        396
#define IDC_REFB                        397
#define IDD_FORMULA                     398
#define IDC_REFC                        399
#define IDD_SCREWMAP                    400
#define IDC_REFXSPEED                   401
#define IDD_MOTORTUNING                 402
#define IDC_REFYSPEED                   403
#define IDC_REFZSPEED                   404
#define IDD_PROCESSOR                   405
#define IDC_REFASPEED                   406
#define IDR_MENU1                       407
#define IDC_REFBSPEED                   408
#define IDR_TOOLPROCESS                 409
#define IDC_REFCSPEED                   410
#define IDC_FULLSPEED                   411
#define IDC_REFNX                       412
#define IDC_REFNY                       413
#define IDC_REFNZ                       414
#define IDC_REFNA                       415
#define IDC_REFNB                       416
#define IDC_REFNC                       417
#define IDC_REFALL                      418
#define IDC_NEWSETTING                  419
#define IDC_EXCZ                        420
#define IDC_BACKX                       421
#define IDC_BACKY                       422
#define IDC_BACKZ                       423
#define IDC_BACKA                       424
#define IDC_BACKB                       425
#define IDC_BACKC                       426
#define IDC_BACKSPEED                   427
#define IDC_BLOFF                       428
#define IDC_BLON                        429
#define IDC_TOOLGRID                    430
#define IDC_AUTOZERO                    431
#define IDC_TOOLNUMBER                  432
#define IDC_FEED                        433
#define IDC_SPINDLE                     434
#define IDC_TEXT                        435
#define IDC_ELASEDTIME                  436
#define IDC_APPLY                       437
#define IDC_SELECT                      438
#define IDC_RESETINTERP                 439
#define IDC_DROLOCK                     440
#define IDC_ZINHIBIT                    441
#define IDC_INHDEPTH                    442
#define IDC_OFFSET                      443
#define IDC_SAFEZ                       444
#define IDC_IGNORETOOL                  445
#define IDC_DOTOOL                      446
#define IDC_MDICONTROL                  447
#define IDC_OVERVIEW                    448
#define IDC_DETAILVIEW                  449
#define IDC_MODE                        450
#define IDC_MODE2                       451
#define IDC_MODE3                       452
#define IDC_MDILIST                     453
#define IDC_LOOKAHEAD                   454
#define IDC_CHANGELOOK                  455
#define IDC_NEWLOOK                     456
#define IDC_AANG                        457
#define IDC_BANG                        458
#define IDC_CANG                        459
#define IDC_MACH1PATHCTRL1              460
#define IDC_MINX                        461
#define IDC_MAXX                        462
#define IDC_DIMENSIONS                  463
#define IDC_SETLENGTH                   464
#define IDC_USEOFFSET                   465
#define IDC_MINA                        466
#define IDC_MINZ                        467
#define IDC_MAXZ                        468
#define IDC_MAXA                        469
#define IDC_MINB                        470
#define IDC_MAXB                        471
#define IDC_MINC                        472
#define IDC_MAXC                        473
#define IDC_ZOOM                        474
#define IDC_TURNOFF                     475
#define IDC_AUTOESTOP                   476
#define IDC_LIMITSOFF                   477
#define IDC_JOYON                       478
#define IDC_OPTSTOP                     479
#define IDR_ZPLASMA                     480
#define IDC_PROGRAMSAFE                 481
#define IDC_RUND                        482
#define IDC_STOPD                       483
#define IDC_REWINDD                     484
#define IDC_EDITFILE                    485
#define IDC_BROWSE                      486
#define IDC_EDITOR                      487
#define IDC_RADIO1                      488
#define IDC_HOTKEY                      489
#define IDC_ISO1                        490
#define IDC_HKEYCHECK                   491
#define IDC_ZEROCD                      492
#define IDC_ZEROALLD                    493
#define IDC_ACTIVATION1                 494
#define IDC_ACTIVATION2                 495
#define IDC_ACTIVATION3                 496
#define IDC_ACTIVATION4                 497
#define IDC_DIGTRIGGER                  498
#define IDC_INDEXPULSE                  499
#define IDC_LIMITTRIGGER                500
#define IDC_TEST                        501
#define IDC_MACRO                       502
#define IDC_MACROLIST                   503
#define IDC_SAVEMACRO                   504
#define IDC_SPINCWD                     505
#define IDC_SPINCCWD                    506
#define IDC_SPINOFFD                    507
#define IDC_AVAILABLE                   508
#define IDC_MISTD                       509
#define IDC_XPOS                        510
#define IDC_FLOODD                      511
#define IDC_YPOS                        512
#define IDC_INCD                        513
#define IDC_ZPOS                        514
#define IDC_RESETD                      515
#define IDC_APOS                        516
#define IDC_REFERENCED                  517
#define IDC_BPOS                        518
#define IDC_GOTOZEROD                   519
#define IDC_CPOS                        520
#define IDC_PWM                         521
#define IDC_PULLEY                      522
#define IDC_PULLEY1                     523
#define IDC_PULLEY2                     524
#define IDC_PULLEY3                     525
#define IDC_PULLEY4                     526
#define IDC_RATIO1                      527
#define IDC_RATIO2                      528
#define IDC_RATIO3                      529
#define IDC_RATIO4                      530
#define IDC_COLORREF                    531
#define IDC_LOW1                        532
#define IDC_COLORUNREF                  533
#define IDC_LOW2                        534
#define IDC_VERIFY                      535
#define IDC_COLORBAC                    536
#define IDC_LOW3                        537
#define IDC_ANSWER                      538
#define IDC_LOW4                        539
#define IDC_QUESTEXT                    540
#define IDC_GUIDE                       541
#define IDC_GOUGECHECK                  542
#define IDC_ORIGINS2                    543
#define IDC_MACHINECOOR                 544
#define IDC_POINTCLOUD                  545
#define IDC_CREATE                      546
#define IDC_XSTEP                       547
#define IDC_YSTEP                       548
#define IDC_ZMAX                        549
#define IDC_ZMIN                        550
#define IDC_ZSAFE                       551
#define IDC_XLR                         552
#define IDC_ZMMIN                       553
#define IDC_YLR                         554
#define IDC_XUL                         555
#define IDC_YUL                         556
#define IDC_SMARTSCAN                   557
#define IDC_SOFTLIMITS                  558
#define IDC_XMAX                        559
#define IDC_YMAX                        560
#define IDC_SOFTLIMIT                   561
#define IDC_HOTKEYSON                   562
#define IDC_XSAFE                       563
#define IDC_CHECK1                      564
#define IDC_LCD                         565
#define IDC_LINEAR                      566
#define IDC_THC                         567
#define IDC_YSAFE                       568
#define IDC_COMPASS                     569
#define IDC_DROMEMORY                   570
#define IDC_LATHE                       571
#define IDC_INPUT0                      572
#define IDC_ENCODER1                    573
#define IDC_XMIN                        574
#define IDC_OEMTRIG3                    575
#define IDC_MPG2                        576
#define IDC_ENCODER2                    577
#define IDC_YMIN                        578
#define IDC_OEMTRIG6                    579
#define IDC_ENCODER3                    580
#define IDC_ZERO1                       581
#define IDC_ZERO2                       582
#define IDC_ZERO3                       583
#define IDC_TODRO1                      584
#define IDC_TODRO2                      585
#define IDC_TODRO3                      586
#define IDC_FROMDRO                     587
#define IDC_FROMDRO2                    588
#define IDC_PASSWORD                    589
#define IDC_FROMDRO3                    590
#define IDC_OVERRIDED                   591
#define IDC_PRIMARY                     592
#define IDC_PRIX                        593
#define IDC_PRIMARY2                    594
#define IDC_BUTTON1                     595
#define IDC_PRIMARY3                    596
#define IDC_ADIAMETER                   597
#define IDC_SENDACQ                     598
#define IDC_DISALL                      599
#define IDC_BDIAMETER                   600
#define IDC_RELOADALL                   601
#define IDC_PRIY                        602
#define IDC_CDIAMETER                   603
#define IDC_PRIZ                        604
#define IDC_SLAVE                       605
#define IDC_DROSELECT                   606
#define IDC_SLAVEY                      607
#define IDC_DROCODE                     608
#define IDC_SLAVEZ                      609
#define IDC_MDISELECT                   610
#define ID_OK                           611
#define IDC_INPUT1                      612
#define IDC_MDICODE                     613
#define IDC_OK                          614
#define IDC_INPUT2                      615
#define IDC_SLAVEM1                     616
#define IDC_LOADGCODE                   617
#define IDC_INPUT3                      618
#define IDC_SLAVEY2                     619
#define IDC_POSX                        620
#define IDC_GCODE                       621
#define IDC_INPUT4                      622
#define IDC_SLAVEZ2                     623
#define IDC_XPCODE                      624
#define IDC_POSY                        625
#define IDC_INPUT5                      626
#define IDC_SLAVEM2                     627
#define IDC_YPCODE                      628
#define IDC_POSZ                        629
#define IDC_INPUT6                      630
#define IDC_SLAVEY3                     631
#define IDC_ZPCODE                      632
#define IDC_POSA                        633
#define IDC_INPUT7                      634
#define IDC_SLAVEZ3                     635
#define IDC_APCODE                      636
#define IDC_POSB                        637
#define IDC_INPUT8                      638
#define IDC_BPCODE                      639
#define IDC_POSC                        640
#define IDC_INPUT9                      641
#define IDC_CPCODE                      642
#define IDC_INPUT10                     643
#define IDC_PROGRESS1                   644
#define IDC_INPUT11                     645
#define IDC_DROCODE2                    646
#define IDC_GCODECODE                   647
#define IDC_XMCODE                      648
#define IDC_INPUT12                     649
#define IDC_YMCODE                      650
#define IDC_INPUT13                     651
#define IDC_ZMCODE                      652
#define IDC_INPUT14                     653
#define IDC_AMCODE                      654
#define IDC_PORT1                       655
#define IDC_INPUT15                     656
#define IDC_BMCODE                      657
#define IDC_PORT2                       658
#define IDC_CMCODE                      659
#define IDC_PULSEMODE                   660
#define IDC_PWMBASE                     661
#define IDC_SPINACTUAL                  662
#define IDC_DEBOUNCE                    663
#define IDC_BACKCOLORR                  664
#define IDC_RAPIDCOLORR                 665
#define IDC_G92OFF                      666
#define IDC_FEEDCOLORR                  667
#define IDC_ORIGINSOFF                  668
#define IDC_BACKCOLORG                  669
#define IDC_COM                         670
#define IDC_RAPIDCOLORG                 671
#define IDC_BAUD                        672
#define IDC_FEEDCOLORG                  673
#define IDC_PWMMIN                      674
#define IDC_BACKCOLORB                  675
#define IDC_TOOLOFFSETOFF               676
#define IDC_RUTEX                       677
#define IDC_RAPIDCOLORB                 678
#define IDC_RADIUSCOMPOFF               679
#define IDC_FEEDCOLORB                  680
#define IDC_TUNE                        681
#define IDC_AR                          682
#define IDC_AG                          683
#define IDC_AB                          684
#define IDC_KPX                         685
#define IDC_ER                          686
#define IDC_RELATIVERETURN              687
#define IDC_KIX                         688
#define IDC_EG                          689
#define IDC_KDX                         690
#define IDC_EB                          691
#define IDC_KPY                         692
#define IDC_STEPX                       693
#define IDC_MTR                         694
#define IDC_KIY                         695
#define IDC_MTG                         696
#define IDC_ERRORX                      697
#define IDC_MTB                         698
#define IDC_KDY                         699
#define IDC_KPZ                         700
#define IDC_KIZ                         701
#define IDC_KDZ                         702
#define IDC_KPA                         703
#define IDC_KIA                         704
#define IDC_KDA                         705
#define IDC_PEAKPX                      706
#define IDC_PEAKMX                      707
#define IDC_STEPY                       708
#define IDC_CHECK2                      709
#define IDC_ERRORY                      710
#define IDC_PEAKPY                      711
#define IDC_INDEXDEBOUNCE               712
#define IDC_PEAKMY                      713
#define IDC_INCS0                       714
#define IDC_STEPZ                       715
#define IDC_INCS1                       716
#define IDC_ERRORZ                      717
#define IDC_INCS2                       718
#define IDC_TOOLAUTO                    719
#define IDC_PEAKPZ                      720
#define IDC_INCS3                       721
#define IDC_OEM1LOW                     722
#define IDC_PEAKMZ                      723
#define IDC_INCS4                       724
#define IDC_OEM3                        725
#define IDC_OEM4LOW                     726
#define IDC_STEPA                       727
#define IDC_INCS5                       728
#define IDC_OEM2                        729
#define IDC_ERRORA                      730
#define IDC_INCS6                       731
#define IDC_OEM1                        732
#define IDC_TXBYTES                     733
#define IDC_PEAKPA                      734
#define IDC_INCS7                       735
#define IDC_RXBYTES                     736
#define IDC_OEM4                        737
#define IDC_PEAKMA                      738
#define IDC_INCS8                       739
#define IDC_OEM5                        740
#define IDC_INCS9                       741
#define IDC_TXPERSEC                    742
#define IDC_OEM6                        743
#define IDC_KEYDOWN                     744
#define IDC_XREF                        745
#define IDC_OEM7                        746
#define IDC_KEYUP                       747
#define IDC_YREF                        748
#define IDC_OEM8                        749
#define IDC_INCS10                      750
#define IDC_ZREF                        751
#define IDC_OEM9                        752
#define IDC_AREF                        753
#define IDC_OEM10                       754
#define IDC_TESTON                      755
#define IDC_BREF                        756
#define IDC_OEM11                       757
#define IDC_CREF                        758
#define IDC_OEM12                       759
#define IDC_XCOOR                       760
#define IDC_OEM13                       761
#define IDC_YCOOR                       762
#define IDC_OEM14                       763
#define IDC_ZCOOR                       764
#define IDC_OEM15                       765
#define IDC_ACOOR                       766
#define IDC_XCOORR                      767
#define IDC_QUESTION                    768
#define IDC_YCOORR                      769
#define IDC_LIMITA                      770
#define IDC_ZCOORR                      771
#define IDC_LIMITB                      772
#define IDC_LIMITC                      773
#define IDC_LIMITY                      774
#define IDC_LIMITZ                      775
#define IDC_BUFFER                      776
#define IDC_MRU                         777
#define IDC_ZINHPERSIST                 778
#define IDC_OVPERSIST                   779
#define IDC_DIRECTION                   780
#define IDC_CANCEL                      781
#define IDC_LASERPWM                    782
#define IDC_NOTHC                       783
#define IDC_INITSTRING                  784
#define IDC_INITALL                     785
#define IDC_TIMING                      786
#define IDC_CHECK3                      787
#define IDC_NOANGLE                     788
#define IDC_DIAMETER                    789
#define IDC_SPINDLERELAYONOFF           790
#define IDC_AUTO1                       791
#define IDC_SHOWSOLID                   792
#define IDC_INCLUDEPROGRAM              793
#define IDC_USEDISCR                    794
#define IDC_ORIGIN                      795
#define IDC_AUTO2                       796
#define IDC_TOOLPOS                     797
#define IDC_AUTO3                       798
#define IDC_AUTO4                       799
#define IDC_ROTATIONAL                  800
#define IDC_ATOYOFFSET                  801
#define IDC_ATOZOFFSET                  802
#define IDC_ATOXOFFSET                  803
#define IDC_ADDONS                      804
#define IDC_SOUNDS                      805
#define IDC_CHECK4                      806
#define IDC_INPUTS                      807
#define IDC_OUTPUTS                     808
#define IDC_MAXCL                       809
#define IDC_CHARGE2                     810
#define IDC_JOGFOLLOW                   811
#define IDC_AROTSON                     812
#define IDC_JOGPERSIST                  813
#define IDC_NOZS                        814
#define IDC_SLOWMODE                    815
#define IDC_GLIST                       816
#define IDC_PERSISTOFF                  817
#define IDC_PERSISTDIALOGS              818
#define IDC_G54BACK                     819
#define IDC_AUTOSCREEN                  820
#define IDC_MOTOR0                      821
#define IDC_MOTOR1                      822
#define IDC_ENCS                        823
#define IDC_MOTOR2                      824
#define IDC_MAXNC10                     825
#define IDC_MOTOR3                      826
#define IDC_SIGNALCW                    827
#define IDC_MOTOR4                      828
#define IDC_SIGNALCCW                   829
#define IDC_MOTOR5                      830
#define IDC_SPINDLEDELAY                831
#define IDC_MOTOR6                      832
#define IDC_FLOODMISTONOFF              833
#define IDC_SIGNALFLOOD                 834
#define IDC_SIGNALMIST                  835
#define IDC_CHECK6                      836
#define IDC_SPINCLOSED                  837
#define IDC_CHARGAP                     838
#define IDC_TOOLSHOW                    839
#define IDC_USESPINDLEMOTOR             840
#define IDC_PWMONOFF                    841
#define IDC_STEPDIRONOFF                842
#define IDC_RADIAL                      843
#define IDC_SPINDLEDELAY2               844
#define IDC_DIAM                        845
#define IDC_SPINDLEDELAYCWD             846
#define IDC_TREE_CTRL                   847
#define IDC_SPINDLEDELAYCCWD            848
#define ID_APPLY                        849
#define IDC_CAPTION_BAR                 850
#define IDC_PAGE_FRAME                  851
#define IDC_P                           852
#define IDC_I                           853
#define IDC_TOOLFLIP                    854
#define IDC_                            855
#define IDC_D                           856
#define IDC_DEPTHLASTPASS               857
#define IDC_INFEED                      858
#define IDC_SPRING                      859
#define IDC_MINDEPTH                    860
#define IDC_XCLEAR                      861
#define IDC_FOLLOW                      862
#define IDC_CHAMFER                     863
#define IDC_START_REG1                  864
#define IDC_EDIT7                       865
#define IDC_DEPTHFIRSTPASS              866
#define IDC_SLAVE_ADDRESS1              867
#define IDC_UNITSMIN                    868
#define IDC_INPUT_REG1                  869
#define IDC_ACCELMIN                    870
#define IDC_HOLDING_REG1                871
#define IDC_CVTIME                      872
#define IDC_COIL1                       873
#define IDC_DISCRETE_INPUT1             874
#define IDC_HZ                          875
#define IDC_PORT2INPUT                  876
#define IDC_SPINDGRAPH                  877
#define IDC_PULSESPERREV                878
#define IDC_UPDATE                      879
#define IDC_SETRPM                      880
#define IDC_TRUERPM                     881
#define IDC_AUTOCAL                     882
#define IDC_RATIO                       883
#define IDC_Z25                         884
#define IDC_AXIS1                       885
#define IDC_AXIS2                       886
#define IDC_AXIS3                       887
#define IDC_AXIS4                       888
#define IDC_AXIS5                       889
#define IDC_AXIS6                       890
#define IDC_HOURS                       891
#define IDC_THISSESSION                 892
#define IDC_CUTTYPE                     893
#define IDC_SPINDLEON                   894
#define IDC_INFEEDTYPE                  895
#define IDC_EDIT1                       896
#define IDC_4AXIS                       897
#define IDC_ZCLEAR                      898
#define IDC_PERIOD                      899
#define IDC_DIGLETTER                   900
#define IDC_CUTDEPTH                    901
#define IDC_ACCEL                       902
#define IDC_RMS                         903
#define IDC_SERIALBITS                  904
#define IDC_CV                          905
#define IDC_SPINAVG                     906
#define IDC_FORMULA1                    907
#define IDC_FORMULA2                    908
#define IDC_FORMULA3                    909
#define IDC_FORMULA4                    910
#define IDC_FORMULA5                    911
#define IDC_FORMULA6                    912
#define IDC_TEST1                       913
#define IDC_TEST2                       914
#define IDC_TEST3                       915
#define IDC_TEST4                       916
#define IDC_TEST5                       917
#define IDC_TEST6                       918
#define IDC_V1                          919
#define IDC_V2                          920
#define IDC_V3                          921
#define IDC_V4                          922
#define IDC_V5                          923
#define IDC_V6                          924
#define IDC_V7                          925
#define IDC_V8                          926
#define IDC_MAPGRAPH                    927
#define IDC_CLEAR1                      928
#define IDC_CLEAR2                      929
#define IDC_CLEAR3                      930
#define IDC_ADDCORRECTION               931
#define IDC_READENCODER                 932
#define IDC_RICHEDIT1                   933
#define IDC_MAPAXIS                     934
#define IDC_MAPAXIS2                    935
#define IDC_MAPAXIS3                    936
#define IDC_SCREW1                      937
#define IDC_SCREW2                      938
#define IDC_THCUPDOWN                   939
#define IDC_SCREW3                      940
#define IDC_LASERSTANDBY                941
#define IDC_MOTORGRAPH                  942
#define IDC_AXISC                       943
#define IDC_AXISS                       944
#define IDC_VELSLIDE                    945
#define IDC_STEPS                       946
#define IDC_SAVEAXIS                    947
#define IDC_STEPWIDTH                   948
#define IDC_SAFE_Z                      949
#define IDC_REVERSE                     950
#define IDC_SHERLINE                    951
#define IDC_ADVANCEDCOMP                952
#define IDC_FLASH                       953
#define IDC_IMMEDIATE                   954
#define IDC_SPINCOUNT                   955
#define IDC_SPINMODON                   956
#define IDC_SPINREG                     957
#define IDC_OEMON                       958
#define IDC_OEMREG                      959
#define IDC_SHUTTLE                     960
#define IDC_DIR                         961
#define IDC_LN_COL                      1000
#define IDC_PROFILELIST                 1002
#define IDC_DEPTHS                      1003
#define IDC_OPEN_PORT_BUTTON            1004
#define IDC_CREATEPROFILE               1005
#define IDC_VERSION                     1006
#define IDC_CLOSE_PORT_BUTTON           1007
#define IDC_DELETEPROFILE               1008
#define IDC_NLAYERS                     1009
#define IDC_COMM_PORT                   1010
#define IDC_SCRIPTS                     1011
#define IDC_LAYERDATA                   1012
#define IDC_BAUDRATE                    1013
#define IDC_DXFPLOT1                    1014
#define IDC_ALLLEVELS                   1015
#define IDC_DXFREADER1                  1016
#define IDC_NOLEVELS                    1017
#define IDC_TERMINAL                    1018
#define IDC_READ_SLIDER                 1019
#define IDC_PORT                        1020
#define IDC_OPTOMISE                    1021
#define IDC_ASDRAWN                     1022
#define IDC_VERSION_STATIC              1023
#define IDC_INITCOM                     1024
#define IDC_ACQCOM                      1025
#define IDC_ENTS                        1026
#define IDC_SENDINIT                    1027
#define IDC_RAPID                       1028
#define IDC_DBITS                       1029
#define IDC_MESSAGELINE                 1030
#define IDC_FILE                        1031
#define IDC_STOPBITS                    1032
#define IDC_PLASMA                      1033
#define IDC_HOMANN                      1034
#define IDC_VECTOR8                     1035
#define IDC_TOLER                       1036
#define IDC_VECTOR0ON                   1037
#define IDC_EDIT3                       1038
#define IDC_PHASE                       1039
#define IDC_MAVG                        1040
#define IDC_PARANUM                     1041
#define IDC_NEWVEC0ON                   1042
#define IDC_NEWVEC8ON                   1043
#define IDC_CALMAX                      1044
#define IDC_OLDCONSTANTON               1045
#define IDC_MAXSPEED                    1046
#define IDC_NEWCONSTANTON               1047
#define IDC_CALCULATE                   1048
#define IDC_RUNNING                     1049
#define IDC_CALDETENT                   1050
#define IDC_WATCHDOG8                   1051
#define IDC_DETENTSIZE                  1052
#define IDC_WATCHDOG0                   1053
#define IDC_CALSWITCH                   1054
#define IDC_VEC8                        1055
#define IDC_SWITCHOVER                  1056
#define IDC_VEC0                        1057
#define IDC_MPG                         1058
#define IDC_NEWVEC0                     1059
#define IDC_NEWVEC8                     1060
#define IDC_MESSAGE                     1061
#define IDC_OLDTIME                     1062
#define IDC_NEWTIME                     1063
#define IDC_MESSAGES                    1064
#define IDC_TICKS                       1065
#define IDC_NAME                        1066
#define IDC_GRAPH                       1067
#define IDC_RECONNECT                   1068
#define IDC_IPADDRESS2                  1069
#define IDC_BOARDID                     1070
#define IDC_PORT1ENABLED                1071
#define IDC_NETMASK                     1072
#define IDC_PORT2ENABLED                1073
#define IDC_EDIT2                       1074
#define IDC_FPGA                        1075
#define IDC_PORT1ADDRESS                1076
#define IDC_INBITS                      1077
#define IDC_PORT2ADDRESS                1078
#define IDC_OUTBITS                     1079
#define IDC_ANAIN                       1080
#define IDC_XON                         1081
#define IDC_ANAOUT                      1082
#define IDC_NEWIP                       1083
#define IDC_LIMITXMIN                   1084
#define IDC_NEWMASK                     1085
#define IDC_YON                         1086
#define IDC_LIMITYMIN                   1087
#define IDC_RX                          1088
#define IDC_LIMITZMIN                   1089
#define IDC_MACROPUMP                   1090
#define IDC_SPINAXISON                  1091
#define IDC_LIMITAMIN                   1092
#define IDC_FORCEIP                     1093
#define IDC_LIMITXPIN                   1094
#define IDC_PERM                        1095
#define IDC_ZON                         1096
#define IDC_LIMITYPIN                   1097
#define IDC_LIMITZPIN                   1098
#define IDC_SENDCONFIG                  1099
#define IDC_LIMITAPIN                   1100
#define IDC_LIMITBPIN                   1101
#define IDC_LIMITBMIN                   1102
#define IDC_PROTOCOL                    1103
#define IDC_LIMITCPIN                   1104
#define IDC_LIMITCMIN                   1105
#define IDC_USELCD                      1106
#define IDC_USEANA                      1107
#define IDC_USEPUMP                     1108
#define IDC_DEBUG                       1109
#define IDC_ACTIVATE1IN                 1110
#define IDC_ACTIVATE2IN                 1111
#define IDC_CONFIGHOMAN                 1112
#define IDC_ACTIVATE3IN                 1113
#define IDC_DIGITIZEIN                  1114
#define IDC_PUMP                        1115
#define IDC_INDEXIN                     1116
#define IDC_FLASHMASK                   1117
#define IDC_HOMEXIN                     1118
#define IDC_BITPACKREG                  1119
#define IDC_HOMEYIN                     1120
#define IDC_BITPACK1                    1121
#define IDC_HOMEZIN                     1122
#define IDC_BITPACKOUT1                 1123
#define IDC_OVERRIDE2                   1124
#define IDC_HOMEAIN                     1125
#define IDC_BITPACKOUTREG1              1126
#define IDC_HOMEBIN                     1127
#define IDC_USERTS                      1128
#define IDC_HOMECIN                     1129
#define IDC_SUBJECT                     1130
#define IDC_EMERGENCY                   1131
#define IDC_DESCRIPTION                 1132
#define IDC_ENCODERXIN                  1133
#define IDC_INCLUDEMILL                 1134
#define IDC_ENCODERYIN                  1135
#define IDC_INCLUDETURN                 1136
#define IDC_ENCODERZIN                  1137
#define IDC_OEMTRIG1                    1138
#define IDC_MATRIX                      1139
#define IDC_OEMTRIG2                    1140
#define IDC_ENHANCED                    1141
#define IDC_OEMTRIG4                    1142
#define IDC_ACTIVATE4IN                 1143
#define IDC_LIMITERR                    1144
#define IDC_LIMITOVERIN                 1145
#define IDC_TIMEOUT                     1146
#define IDC_PINAVAILIN                  1147
#define IDC_SERIAL                      1148
#define IDC_CON                         1149
#define IDC_OEMTRIG5                    1150
#define IDC_USECR                       1151
#define IDC_BON                         1152
#define IDC_CHAR                        1153
#define IDC_AON                         1154
#define IDC_DIGITIZEOUT                 1155
#define IDC_ENABLE1OUT                  1156
#define IDC_HISTORY                     1157
#define IDC_ENABLE2OUT                  1158
#define IDC_SLS5000                     1159
#define IDC_ENABLE3OUT                  1160
#define IDC_ENABLE4OUT                  1161
#define IDC_AXIS0                       1162
#define IDC_ENABLE5OUT                  1163
#define IDC_ENABLE6OUT                  1164
#define IDC_DUTYCYLE                    1165
#define IDC_ACTIVATE1OUT                1166
#define IDC_DUTYCYLE1                   1167
#define IDC_ACTIVATE2OUT                1168
#define IDC_DUTYCYLE2                   1169
#define IDC_ACTIVATE3OUT                1170
#define IDC_DUTYCYLE3                   1171
#define IDC_PINOUTAVAIL                 1172
#define IDC_DUTYCYLE4                   1173
#define IDC_LIMITX                      1174
#define IDC_ACTIVATE4OUT                1175
#define IDC_DIVIDER                     1176
#define IDC_LIMITXMINUS                 1177
#define IDC_ACTIVATE5OUT                1178
#define IDC_COUNTERTRIGGER              1179
#define IDC_LIMITYPLUS                  1180
#define IDC_ACTIVATE3OUT2               1181
#define IDC_ACTIVATE6OUT                1182
#define IDC_INTINC                      1183
#define IDC_LIMITYMINUS                 1184
#define IDC_EXTINC                      1185
#define IDC_LIMITZPLUS                  1186
#define IDC_LIMITZMINUS                 1187
#define IDC_READREX                     1188
#define IDC_LIMITAPLUS                  1189
#define IDC_LIMITAMINUS                 1190
#define IDC_READSETUP                   1191
#define IDC_LIMITBPLUS                  1192
#define IDC_ZEROM3                      1193
#define IDC_LIMITBMINUS                 1194
#define IDC_HOLDON1                     1195
#define IDC_LIMITCPLUS                  1196
#define IDC_MPG1                        1197
#define IDC_LIMITCMINUS                 1198
#define IDC_WATCHDOGS                   1199
#define IDC_HOMEX                       1200
#define IDC_END                         1201
#define IDC_HOMEY                       1202
#define IDC_VELUNIT                     1203
#define IDC_HOMEZ                       1204
#define IDC_ACCUNIT                     1205
#define IDC_HOMEA                       1206
#define IDC_SHORTROT                    1207
#define IDC_HOMEB                       1208
#define IDC_HW_SAFE                     1209
#define IDC_HOMEC                       1210
#define IDC_LIMITSOV                    1211
#define IDC_DEBUGOFF                    1212
#define IDC_INDEX                       1213
#define IDC_MPG2HI                      1214
#define IDC_THCOn                       1215
#define IDC_DIGIOFF                     1216
#define IDC_RAISE                       1217
#define IDC_FREQOFF                     1218
#define IDC_LOWER                       1219
#define IDC_MPG1HI                      1220
#define IDC_ACCTIME                     1221
#define IDC_OEM2LOW                     1222
#define IDC_VOLTAGE1                    1223
#define IDC_OEM3LOW                     1224
#define IDC_VOLTAGE2                    1225
#define IDC_TORCH                       1226
#define IDC_OEM5LOW                     1227
#define IDC_VOLTAGE3                    1228
#define IDC_KEYPAD                      1229
#define IDC_OEM6LOW                     1230
#define IDC_VOLTAGE4                    1231
#define IDC_VOLTAGE5                    1232
#define IDC_VOLTAGE6                    1233
#define IDC_MODBUSLIST                  1234
#define IDC_ESTOP                       1235
#define IDC_VOLTAGE7                    1236
#define IDC_DIGITIZE                    1237
#define IDC_VOLTAGE8                    1238
#define IDC_VIDEOOCXCTRL1               1239
#define IDC_ACTIVE1                     1240
#define IDC_VOLTAGE9                    1241
#define IDC_VIDEOOCXTOOLSCTRL2          1242
#define IDC_ACTIVE2                     1243
#define IDC_VOLTAGE10                   1244
#define IDC_SETCAMERA                   1245
#define IDC_ACTIVE3                     1246
#define IDC_BUTTONSTART                 1247
#define IDC_ACTIVE4                     1248
#define IDC_BUTTONSTOP                  1249
#define IDC_EDGEMAG                     1250
#define IDC_EDGEDIR                     1251
#define IDC_MOTION                      1252
#define IDC_LIMITXPLUSPIN               1253
#define IDC_FLIP                        1254
#define IDC_LIMITXMINUSPORT             1255
#define IDC_ORIGINAL                    1256
#define IDC_LIMITXMINUSPIN              1257
#define IDC_CROSSHAIR                   1258
#define IDC_LIMITYPLUSPORT              1259
#define IDC_RESETIO                     1260
#define IDC_LIMITYPLUSPIN               1261
#define IDC_SERVOSERIAL                 1262
#define IDC_LIMITYMINUSPORT             1263
#define IDC_SERIALSTATUS                1264
#define IDC_LIMITYMINUSPIN              1265
#define IDC_AUTOCONNECT                 1266
#define IDC_LIMITZPLUSPORT              1267
#define IDC_CONNECT                     1268
#define IDC_LIMITZPLUSPIN               1269
#define IDC_RESETRING                   1270
#define IDC_LIMITZMINUSPORT             1271
#define IDC_MESSCNT                     1272
#define IDC_LIMITZMINUSPIN              1273
#define IDC_INITRING                    1274
#define IDC_LIMITAPLUSPORT              1275
#define IDC_NDRIVES                     1276
#define IDC_LIMITAPLUSPIN               1277
#define IDC_DRIVESELECT                 1278
#define IDC_LIMITAMINUSPORT             1279
#define IDC_LIMITAMINUSPIN              1280
#define IDC_REFRESHDATA                 1281
#define IDC_LIMITXPLUSPORT              1282
#define IDC_DATASTATUS                  1283
#define IDC_FIRMWARE                    1284
#define IDC_ENABLE1                     1285
#define IDC_BIT0                        1286
#define IDC_ENABLE2                     1287
#define IDC_BIT1                        1288
#define IDC_ENABLE3                     1289
#define IDC_BIT2                        1290
#define IDC_ENABLE4                     1291
#define IDC_BIT3                        1292
#define IDC_ENABLE5                     1293
#define IDC_BIT4                        1294
#define IDC_ENABLE6                     1295
#define IDC_BIT5                        1296
#define IDC_EXTERN1                     1297
#define IDC_BIT6                        1298
#define IDC_EXTERN2                     1299
#define IDC_BIT7                        1300
#define IDC_LIMITBPLUSPORT              1301
#define IDC_EXTERN3                     1302
#define IDC_BIT8                        1303
#define IDC_LIMITBPLUSPIN               1304
#define IDC_DIGPORT                     1305
#define IDC_BIT9                        1306
#define IDC_LIMITBMINUSPORT             1307
#define IDC_DIGPIN                      1308
#define IDC_ENC1APORT                   1309
#define IDC_BIT10                       1310
#define IDC_LIMITBMINUSPIN              1311
#define IDC_XPORT                       1312
#define IDC_ENC1BPORT                   1313
#define IDC_BIT11                       1314
#define IDC_LIMITCPLUSPORT              1315
#define IDC_XPIN                        1316
#define IDC_ENC1APIN                    1317
#define IDC_BIT12                       1318
#define IDC_LIMITCPLUSPIN               1319
#define IDC_YPORT                       1320
#define IDC_ENC1BPIN                    1321
#define IDC_BIT13                       1322
#define IDC_LIMITCMINUSPORT             1323
#define IDC_YPIN                        1324
#define IDC_ENC2APORT                   1325
#define IDC_BIT14                       1326
#define IDC_LIMITCMINUSPIN              1327
#define IDC_ZPORT                       1328
#define IDC_ENC2BPORT                   1329
#define IDC_BIT15                       1330
#define IDC_HOMEYPORT                   1331
#define IDC_ZPIN                        1332
#define IDC_ENC2APIN                    1333
#define IDC_BIT16                       1334
#define IDC_HOMEYPIN                    1335
#define IDC_APORT                       1336
#define IDC_ENC2BPIN                    1337
#define IDC_BIT17                       1338
#define IDC_HOMEXPORT                   1339
#define IDC_APIN                        1340
#define IDC_ENC3APORT                   1341
#define IDC_BIT18                       1342
#define IDC_HOMEXPIN                    1343
#define IDC_BPORT                       1344
#define IDC_ENC3BPORT                   1345
#define IDC_BIT19                       1346
#define IDC_BPIN                        1347
#define IDC_ENC3APIN                    1348
#define IDC_BIT20                       1349
#define IDC_CPORT                       1350
#define IDC_ENC3BPIN                    1351
#define IDC_BIT21                       1352
#define IDC_EMERGENCYPORT               1353
#define IDC_CPIN                        1354
#define IDC_BIT22                       1355
#define IDC_ESTOPPIN                    1356
#define IDC_EX1PORT                     1357
#define IDC_BIT23                       1358
#define IDC_INDEXPORT                   1359
#define IDC_EX1PIN                      1360
#define IDC_BIT24                       1361
#define IDC_INDEXPIN                    1362
#define IDC_EX2PORT                     1363
#define IDC_BIT25                       1364
#define IDC_EX2PIN                      1365
#define IDC_TIMINGPORT                  1366
#define IDC_BIT26                       1367
#define IDC_EX3PORT                     1368
#define IDC_TIMINGPIN                   1369
#define IDC_BIT27                       1370
#define IDC_EX3PIN                      1371
#define IDC_BIT28                       1372
#define IDC_XSTEPNEG                    1373
#define IDC_BIT29                       1374
#define IDC_XDIRNEG                     1375
#define IDC_BIT30                       1376
#define IDC_YSTEPNEG                    1377
#define IDC_BIT31                       1378
#define IDC_YDIRNEG                     1379
#define IDC_BIT32                       1380
#define IDC_ZSTEPNEG                    1381
#define IDC_CLEARSHUT                   1382
#define IDC_ZDIRNEG                     1383
#define IDC_CURSPEED                    1384
#define IDC_ASTEPNEG                    1385
#define IDC_CURPOS                      1386
#define IDC_ADIRNEG                     1387
#define IDC_PDN                         1388
#define IDC_BSTEPNEG                    1389
#define IDC_PUP                         1390
#define IDC_BDIRNEG                     1391
#define IDC_PARAMVAL                    1392
#define IDC_CSTEPNEG                    1393
#define IDC_PMEAN                       1394
#define IDC_CDIRNEG                     1395
#define IDC_SET                         1396
#define IDC_XSTEPPORT                   1397
#define IDC_TORCHVOLTS                  1398
#define IDC_XSTEPPIN                    1399
#define IDC_XDIRPORT                    1400
#define IDC_REVERSEARC                  1401
#define IDC_XDIRPIN                     1402
#define IDC_KEEPREF                     1403
#define IDC_YSTEPPORT                   1404
#define IDC_MPG3                        1405
#define IDC_HOMECPORT                   1406
#define IDC_YSTEPPIN                    1407
#define IDC_G                           1408
#define IDC_HOMECPIN                    1409
#define IDC_YDIRPORT                    1410
#define IDC_G20COOR1                    1411
#define IDC_HOMEBPORT                   1412
#define IDC_YDIRPIN                     1413
#define IDC_G20COOR2                    1414
#define IDC_TPERSIT                     1415
#define IDC_HOMEBPIN                    1416
#define IDC_ZSTEPPORT                   1417
#define IDC_G20COOR3                    1418
#define IDC_BOXED                       1419
#define IDC_HOMEAPORT                   1420
#define IDC_ZSTEPPIN                    1421
#define IDC_G20COOR4                    1422
#define IDC_DROFONT                     1423
#define IDC_HOMEAPIN                    1424
#define IDC_ZDIRPORT                    1425
#define IDC_G20COOR5                    1426
#define IDC_DROBUDDY                    1427
#define IDC_HOMEZPORT                   1428
#define IDC_ZDIRPIN                     1429
#define IDC_G20COOR6                    1430
#define IDC_DROLABEL                    1431
#define IDC_HOMEZPIN                    1432
#define IDC_ASTEPPORT                   1433
#define IDC_LABELBUDDY                  1434
#define IDC_ROT360                      1435
#define IDC_DIGITIZEPORT                1436
#define IDC_ASTEPPIN                    1437
#define IDC_CODEFONT                    1438
#define IDC_NOWARN                      1439
#define IDC_DIGITIZEPIN                 1440
#define IDC_ADIRPORT                    1441
#define IDC_CODEBUDDY                   1442
#define IDC_NURBS                       1443
#define IDC_LIMITSOVERPORT              1444
#define IDC_ADIRPIN                     1445
#define IDC_HIRES                       1446
#define IDC_BUTTONFONT                  1447
#define IDC_LIMITOVERPIN                1448
#define IDC_BSTEPPORT                   1449
#define IDC_PATHLINES                   1450
#define IDC_BUTTONBUDDY                 1451
#define IDC_ACTIVE1PORT                 1452
#define IDC_BSTEPPIN                    1453
#define IDC_UDP                         1454
#define IDC_ACTIVE1PIN                  1455
#define IDC_BDIRPORT                    1456
#define IDC_ACTIVE2PORT                 1457
#define IDC_BDIRPIN                     1458
#define IDC_ACTIVE2PIN                  1459
#define IDC_CSTEPPORT                   1460
#define IDC_GRID                        1461
#define IDC_ACTIVE3PORT                 1462
#define IDC_CSTEPPIN                    1463
#define IDC_ACTIVE3PIN                  1464
#define IDC_CDIRPORT                    1465
#define IDC_ACTIVE4PORT                 1466
#define IDC_CDIRPIN                     1467
#define IDC_NPORT                       1468
#define IDC_ACTIVE4PIN                  1469
#define IDC_SPINDLESTEP                 1470
#define IDC_IPADDRESS1                  1471
#define IDC_SPINDLEDIR                  1472
#define IDC_LOWERPORT                   1473
#define IDC_MODPLUG                     1474
#define IDC_SPSTEPPORT                  1475
#define IDC_XAXIS                       1476
#define IDC_LOWERPIN                    1477
#define IDC_NOT                         1478
#define IDC_SPSTEPPIN                   1479
#define IDC_YAXIS                       1480
#define IDC_RAISEPORT                   1481
#define IDC_AXISB                       1482
#define IDC_YES                         1483
#define IDC_SPDIRPORT                   1484
#define IDC_ZAXIS                       1485
#define IDC_AREV                        1486
#define IDC_RAISEPIN                    1487
#define IDC_AXISA                       1488
#define IDC_DONTASK                     1489
#define IDC_SPDIRPIN                    1490
#define IDC_CAXIS                       1491
#define IDC_BREV                        1492
#define IDC_TORCHONPORT                 1493
#define IDC_AXISZ                       1494
#define IDC_AAXIS                       1495
#define IDC_CHARGEPORT                  1496
#define IDC_TORCHONPIN                  1497
#define IDC_AXISY                       1498
#define IDC_BAXIS                       1499
#define IDC_CHARGEPIN                   1500
#define IDC_OEMPORT3                    1501
#define IDC_AXISX                       1502
#define IDC_VELOCITY                    1503
#define IDC_OEMPIN3                     1504
#define IDC_EXTERN4                     1505
#define IDC_ACCELERATION                1506
#define IDC_ACCELERATE                  1507
#define IDC_OEMPORT2                    1508
#define IDC_EXTERN5                     1509
#define IDC_VELOCITYEDIT                1510
#define IDC_CURX                        1511
#define IDC_OEMPIN2                     1512
#define IDC_EXTERN6                     1513
#define IDC_ACCEDIT                     1514
#define IDC_CURY                        1515
#define IDC_OEMPORT1                    1516
#define IDC_EX4PORT                     1517
#define IDC_STEPSPERUNIT                1518
#define IDC_CURZ                        1519
#define IDC_OEMPIN1                     1520
#define IDC_EX4PIN                      1521
#define IDC_MMS                         1522
#define IDC_CURA                        1523
#define IDC_OEMPORT4                    1524
#define IDC_EX5PORT                     1525
#define IDC_NTGRAPHCTRL1                1526
#define IDC_INCHES                      1527
#define IDC_CURB                        1528
#define IDC_OEMPIN4                     1529
#define IDC_EX5PIN                      1530
#define IDC_DEVICE                      1531
#define IDC_UNITTEXT                    1532
#define IDC_CURC                        1533
#define IDC_OEMPORT5                    1534
#define IDC_EX6PORT                     1535
#define IDC_DEVICE1                     1536
#define IDC_CURRENT                     1537
#define IDC_CURX2                       1538
#define IDC_OEMPIN5                     1539
#define IDC_EX6PIN                      1540
#define IDC_DEVICE2                     1541
#define IDC_SAVE                        1542
#define IDC_CURY2                       1543
#define IDC_OEMPORT6                    1544
#define IDC_CHARGEPORT2                 1545
#define IDC_DEVICE3                     1546
#define IDC_DIAMFEEDRATE                1547
#define IDC_PULSEWIDTH                  1548
#define IDC_CURZ2                       1549
#define IDC_OEMPIN6                     1550
#define IDC_CHARGEPIN2                  1551
#define IDC_DEVICE4                     1552
#define IDC_DIRWIDTH                    1553
#define IDC_CURA2                       1554
#define IDC_MIN                         1555
#define IDC_CURB2                       1556
#define IDC_MAX                         1557
#define IDC_CURC2                       1558
#define IDC_REV                         1559
#define IDC_CURID                       1560
#define IDC_MACHINE                     1561
#define IDC_NEXTID                      1562
#define IDC_WORK                        1563
#define IDC_LOAD                        1564
#define IDC_INCR                        1565
#define IDC_ALLOWSAFE                   1566
#define IDC_SAFEZDRO                    1567
#define IDC_ONSTOP                      1568
#define IDC_SLAVEM0                     1569
#define IDC_CVDIST                      1570
#define IDC_SPINOFF                     1571
#define IDC_SPININC                     1572
#define IDC_CVANGLE                     1573
#define IDC_RADIO2                      1574
#define IDC_XHOME                       1575
#define IDC_CVANGGLEDEG                 1576
#define IDC_DROUNITS                    1577
#define IDC_OVSPININC                   1578
#define IDC_RADIO4                      1579
#define IDC_COUNTS                      1580
#define IDC_YHOME                       1581
#define IDC_PULLBACKG73                 1582
#define IDC_RADIO6                      1583
#define IDC_COMBO1                      1584
#define IDC_BLIMM                       1585
#define IDC_NOMENU                      1586
#define IDC_RADIO8                      1587
#define IDC_THC5                        1588
#define IDC_RADIO9                      1589
#define IDC_AGREEMENT                   1590
#define IDC_RADIO10                     1591
#define IDC_ICHECK6                     1592
#define IDC_KEYCLICK                    1593
#define IDC_RADIO11                     1594
#define IDC_CANCELAUTO                  1595
#define IDC_RADIO12                     1596
#define IDC_ASMESS                      1597
#define IDC_RADIO13                     1598
#define IDC_AUTOSET                     1599
#define IDC_RADIO14                     1600
#define IDC_BHOME                       1601
#define IDC_PDATA                       1602
#define IDC_RADIO15                     1603
#define IDC_AUTOMATE                    1604
#define IDC_DECELMULT                   1605
#define IDC_RADIO17                     1606
#define IDC_FIXME                       1607
#define IDC_RADIO18                     1608
#define IDC_JOGHEAT                     1609
#define IDC_AXIS                        1610
#define IDC_DELETE                      1611
#define IDC_ENTRY                       1612
#define IDC_LOCK                        1613
#define IDC_ID1                         1614
#define IDC_BUTTON2                     1615
#define IDC_HORIZ1                      1616
#define IDC_HERTZ                       1617
#define IDC_HORIZ2                      1618
#define IDC_SLAVEDISCONNECT             1619
#define IDC_PROBETLO                    1620
#define IDC_HHOTPLUS                    1621
#define IDC_ROTSOFT                     1622
#define IDC_HHOTMINUS                   1623
#define IDC_KEY                         1624
#define IDC_VHOTPLUS                    1625
#define IDC_TCPGRID                     1626
#define IDC_HORIZ3                      1627
#define IDC_HORIZ4                      1628
#define IDC_TCPMODBUS                   1629
#define IDC_HORIZ5                      1630
#define IDC_MASTERADDRESS               1631
#define IDC_HORIZ6                      1632
#define IDC_SMTXCTRL1                   1633
#define IDC_VERT1                       1634
#define IDC_IPADDRESS                   1635
#define IDC_HORIZ8                      1636
#define IDC_ENABLED                     1637
#define IDC_HORIZ9                      1638
#define IDC_BRAINS                      1639
#define IDC_HORIZ10                     1640
#define IDC_ENALL                       1641
#define IDC_HORIZ11                     1642
#define IDC_RELOADONE                   1643
#define IDC_HORIZ12                     1644
#define IDC_VIEWBRAIN                   1645
#define IDC_VHOTMINUS                   1646
#define IDC_MODBUS                      1647
#define IDD_MAIN_DLG                    1648
#define IDD_PROFILER                    2130
#define IDD_CREATEPROFILE               2136
#define IDD_TCPMODDIAG                  2137
#define IDC_SLAVE_ADDRESS               2307
#define IDC_DATA                        2308
#define IDC_SLAVE_ADDRESS2              2309
#define IDC_START_REG                   2310
#define IDC_NUM_REG                     2311
#define IDC_INPUT_REG                   2312
#define IDC_HOLDING_REG                 2313
#define IDC_READ                        2314
#define IDC_START_REG2                  2315
#define IDC_WRITE                       2316
#define IDC_INPUT_REG2                  2317
#define IDC_START_REG3                  2318
#define IDC_HOLDING_REG2                2319
#define IDC_START_REG4                  2320
#define IDC_INPUT_REG3                  2321
#define IDC_SLAVE_ADDRESS3              2322
#define IDC_HEX                         2323
#define IDC_SLAVE_ADDRESS4              2324
#define IDC_DECIMAL                     2325
#define IDC_END_REG1                    2326
#define IDC_END_REG2                    2327
#define IDC_END_REG3                    2328
#define IDC_END_REG4                    2329
#define IDC_HOLDING_REG3                2330
#define IDC_COIL                        2331
#define IDC_DISCRETE_INPUT              2332
#define IDC_START                       2333
#define IDC_NUMBER                      2334
#define IDC_COIL2                       2335
#define IDC_DISCRETE_INPUT2             2336
#define IDC_INPUT_REG4                  2337
#define IDC_HOLDING_REG4                2338
#define IDC_REPORT_SLAVE_ID             2339
#define IDC_START5                      2340
#define IDC_READ_EXCEPTION_STATUS_BUTTON 2341
#define IDC_OX_BUTTON_CLEAR             26451
#define IDC_OX_BUTTON_CLEARNUMBER       26452
#define IDC_OX_BUTTON_BACK              26453
#define IDC_OX_BUTTON_7                 26454
#define IDC_OX_BUTTON_8                 26455
#define IDC_OX_BUTTON_9                 26456
#define IDC_OX_BUTTON_4                 26457
#define IDC_OX_BUTTON_5                 26458
#define IDC_OX_BUTTON_6                 26459
#define IDC_OX_BUTTON_1                 26460
#define IDC_OX_BUTTON_2                 26461
#define IDC_OX_BUTTON_3                 26462
#define IDC_OX_BUTTON_DIVIDE            26463
#define IDC_OX_BUTTON_MULTIPLY          26464
#define IDC_OX_BUTTON_SUBTRACT          26465
#define IDC_OX_BUTTON_ADD               26466
#define IDC_OX_BUTTON_EQUAL             26467
#define IDC_OX_BUTTON_0                 26468
#define IDC_OX_BUTTON_CHANGESIGN        26469
#define IDC_OX_BUTTON_DELIMITER         26470
#define IDC_OX_BUTTON_SQRT              26471
#define IDC_OX_BUTTON_MOD               26472
#define IDC_OX_BUTTON_RECIPROCAL        26473
#define IDC_OX_BUTTON_PI                26475
#define IDC_OX_BUTTON_COS               26476
#define IDC_OX_BUTTON_SIN               26477
#define IDC_OX_BUTTON_TAN               26478
#define IDC_OX_BUTTON_COTAN             26479
#define IDC_OX_BUTTON_FACTORIAL         26481
#define IDC_OX_BUTTON_POWER             26483
#define IDC_OX_BUTTON_NATURAL_LOGARITHM 26484
#define IDC_OX_BUTTON_LOGARITHM         26485
#define ID_CONFIGURATION_VELOCITYACCEL  27771
#define ID_FILE_LOADGCODE               27772
#define ID_CONFIGURATION_PORTSANDPINS   27773
#define ID_FILE_IMPORTPHOTO             27774
#define ID_EXIT_EXIT                    27775
#define ID_FILE_IMPORTDXFS              27776
#define ID_UNITS                        27777
#define ID_FILE_CLOSEFILES              27778
#define ID_ADDDRO                       27779
#define ID_FILE_EXIT                    27780
#define ID_SAVELAYOUT                   27781
#define ID_SELECTUNITS                  27782
#define ID_LOADLAY                      27783
#define ID_CONFIGURE_PORTSANDPINS       27784
#define ID_CLEARLAY                     27785
#define ID_CONFIGURE_SOFTLIMITS         27786
#define ID_REWINDSCRIPT                 27787
#define ID_VARIJOG                      27788
#define ID_CONFIGURE_SLAVING            27789
#define ID_CONTROLS_ADDEMERGENCY        27790
#define ID_CONFIGURE_SETAXISHOTKEYS     27791
#define ID_ZERO                         27792
#define ID_CONFIGURE_MOTORCONFIG        27793
#define ID_SET                          27794
#define ID_CONFIGURE_CONFIGUREBACKLASH  27795
#define ID_DISPLAYOPTIONS               27796
#define ID_CONFIG_TOOLPATH              27797
#define ID_DISPLAYOPTIONS_ZERO          27798
#define ID_CONFIGURE_LOGIC              27799
#define ID_CONFIGURE_STATE              27800
#define ID_LAYOUTS_LOADLAYOUT           27801
#define ID_SETTO                        27802
#define ID_VIEW_REGENTOOLPATH           27803
#define ID_WIZARDS_DIGITIZE             27804
#define ID_OPERATOR_CONTROLOFFLINE      27805
#define ID_LOCK                         27806
#define ID_UNLOCK                       27807
#define ID_CONFIGURE_MACROS             27808
#define ID_POPUPTOP_ZERODISPLAY         27809
#define ID_CONFIGURE_FIXTURES           27810
#define ID_POPUPTOP_SETTHISDISPLAY      27811
#define ID_CONFIGURE_TOOLTABLE          27812
#define ID_OPERATOR_CALIBRATESPINDLE    27813
#define ID_POPUPTOP_MACHINECOORDINATES  27814
#define ID_OPERATOR_SCREWMAPPING        27815
#define ID_POPUPTOP_PARTCOORDINATES     27816
#define ID_OPERATOR_FORMULAS            27817
#define ID_OPERATOR_MAINTENANCEHOURS    27818
#define ID_HELP_ABOUTMACH1ENGINE        27819
#define ID_HELP_WWW                     27820
#define ICD_IMPORTHPGL                  27821
#define ID_PROCESSING_COMPENSATION      27822
#define IDC_IMPORTDXF                   27823
#define ID_PROCESSING_BACKLASH          27824
#define CLOSEFILE                       27825
#define IDC_EXIT                        27826
#define ID_SELECT_ALL                   27827
#define IDC_SETNATIVE                   27828
#define IDC_PORTSPINS                   27829
#define ID_BUTTON32807                  27830
#define IDC_HOMINGLIMITS                27831
#define ID_BUTTON32808                  27832
#define IDC_SETHOTKEYS                  27833
#define IDC_TUNEMOTOR                   27834
#define IDC_BACKLASH                    27835
#define IDC_TOOLPATH                    27836
#define IDC_LOGIC                       27837
#define IDC_STATE                       27838
#define IDC_LOADSCREENS                 27839
#define IDC_REGEN                       27840
#define IDC_PICKWIZARD                  27841
#define IDC_OFFLINE                     27842
#define IDC_UNLOCK                      27843
#define IDC_MACROS                      27844
#define IDC_FIXTURES                    27845
#define IDC_TOOLTABLE                   27846
#define IDC_SPINCAL                     27847
#define IDC_SCREWMAP                    27848
#define IDC_FORMULAS                    27849
#define IDC_MAINTENANCE                 27850
#define IDC_ABOUT                       27851
#define IDC_ARTSOFT                     27852
#define ID_OPERATOR_CALIBRATEMPG        27853
#define ID_OPERATOR_MODBUSCONTROL       27854
#define ID_HELP_EMAILSUPPORTREQUEST     27855
#define ID_CONFIG_SERIALMONITOR         27856
#define ID_OPERATOR_VBSCRIPTER          27857
#define ID_OPERATOR_VBSCRIPTEDITOR      27858
#define ID_RUNSCRIPT                    27859
#define ID_STOPSCRIPT                   27860
#define ID_SETBREAK                     27861
#define ID_SINGLESTEP                   27862
#define ID_REMOVEBREAK                  27863
#define ID_VBOFF                        27864
#define ID_SAVESCRIPT                   27865
#define ID_VBFILECLOSE                  27866
#define ID_VBFILEOPEN                   27867
#define ID_EDIT                         27868
#define ID_VB_FIND                      27869
#define ID_VB_REPLACE                   27870
#define ID_EDIT_FINDNEXT                27871
#define ID_VBRUN                        27872
#define ID_DEBUG                        27873
#define ID_DEBUG_STEPINTO               27874
#define ID_DEBUG_STEPOVER               27875
#define ID_DEBUG_END                    27876
#define ID_BREAKPOINTS_SETBREAKPOINT    27877
#define ID_BREAKPOINTS_CLEARBREAKPOINT  27878
#define ID_BREAKPOINTS_CLEARALLBREAKPOINTS 27879
#define ID_BREAKPOINTS_ENUMERATEBREAKPOINTS 27880
#define ID_RUN                          27881
#define ID_RUN_RUN                      27882
#define ID_RUN_STOP                     27883
#define ID_DEBUG_RUN                    27884
#define ID_DEBUG_RESET                  27885
#define ID_FILE_SAVEFILE                27886
#define ID_FILE_SAVEAS                  27887
#define ID_DEBUG_CONTINUE               27888
#define IDM_UNDO                        27889
#define IDM_CUT                         27890
#define IDM_COPY                        27891
#define IDM_PASTE                       27892
#define IDM_CLEAR                       27893
#define IDM_SELALL                      27894
#define ID_FILE_OPTIONS                 27895
#define ID_VIEW_SAVECURRENTLAYOUT       27896
#define ID_CONFIG_GREXCONTROL           27897
#define ID_FILE_DXFTURNIMPORT           27898
#define ID_VIEW_VIDEOWINDOW             27899
#define ID_CONFIG_FONTS                 27900
#define ID_HELP_WWW32894                27901
#define ID_CONFIG_EDITBUTOTNSCRIPT      27902
#define ID_CONFIG_CHECKCONFIG           27903
#define ID_CONFIG_MODBUSCONFIG          27904
#define ID_Menu                         27905
#define ID_CONFIG_GENERALMODBUSCONFIG   27907
#define ID_CONFIG_RESETDEVICESEL        27908
#define ID_CONFIG_SPECIALCONFIGS        27909
#define ID_Menu32903                    27910
#define ID_CONFIG_SPINDLEPULLEYS        27911
#define ID_CONFIG_SAFE                  27912
#define ID_OPERATOR_AUTO                27913
#define ID_OPERATOR_SETNORMALCONDITION  27914
#define ID_VIEW_MANUALENCODERDROSCREEN  27915
#define ID_VIEW_DEFAULTMOTORCONTROLSCREEN 27916
#define ID_OPERATOR_RESTORESETTINGS     27917
#define ID_PLUGINCONTROL                27918
#define ID_PLUGINCONTROLDUMMY           27919
#define ID_CONFIG_SAVESETTINGS          27920
#define ID_OPERATOR_TCPMODBUSCONTROL    27921
#define ID_SCROLLTYPE_SCREENMODE        27924
#define ID_FIRSTBAR                     27925
#define ID_OPERATOR_BRAINEDITOR         27926
#define ID_CONFIGPLUGINS                27928
#define ID_SCROLLTYPE                   27929
#define ID_BRAINCONTROL                 28927

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        962
#define _APS_NEXT_COMMAND_VALUE         27930
#define _APS_NEXT_CONTROL_VALUE         2342
#define _APS_NEXT_SYMED_VALUE           108
#endif
#endif
